### ISSUE TITLE
Get Income statement - not filtering pages with out data

### ISSUE THREAD

**Issue by heyitsfred** [jgQuantScripts/getIncomeStatements#1]
line 71 - you pull pages 2 through 10 for a given ticker - and then filter out the pages without data on line 74.  Yet when I attempted this with ticker RBLX - (only had two pages of data) - it did not filter out pages 3 through 10.  all had identical lengths to 'page 2'  - "2".

I tweaked the code to hard code the # of pages as a crude work around.

**Comment by heyitsfred** [comment]
I swapped your code with this - a little fancier than my crude work around - yet seems to be doing the job.  

```r
  # remove empty lists - removes pages without content
  keep = rep(TRUE, length(pages))
  for (j in 1:length(pages)){
   tmp = pg[j][[1]] %>% html_nodes("table") %>% html_table() %>% as.data.frame()
   if(nrow(tmp)==0) {keep[j] =FALSE} #if there is no dataframe from this URL - remove it
  }
  pg = pg[keep] #only keep the urls with actual data
```

**Comment by jgQuantScripts** [comment]
Pushed Version 2.0 with the modifications. Thanks for your contribution.
