### ISSUE TITLE
Get Rid of Special Characters - not dynamic

### ISSUE THREAD

**Issue by heyitsfred** [jgQuantScripts/getIncomeStatements#2]
When a df has less than 6 columns - the remove special characters step - produces an error.

rewrote to the following: 
```r
 # get rid of special characters
    for (j in 2:ncol(df)){
      df[,j] <- gsub("\\$","",gsub("\\,","",df[,j]))
    }
```

**Comment by jgQuantScripts** [comment]
Pushed Version 2.0 with the modifications. Thanks for your contribution.
