### ISSUE TITLE
Not all the ROWS are 100% populated in BAR chart

### ISSUE THREAD

**Issue by heyitsfred** [jgQuantScripts/getIncomeStatements#3]
there is - sometimes - data reporting issues on BARchart - so some rows (like "Income taxes") may be blank on a given page.  This would cause the lists to have different row lengths - and cause cbind to error out when doing the 'do.call'.

added this code to put in blank cells when no data is present for a given row descriptor

```r
 df = lapply(as.list(1:length(ROWS)), function(ii){
      tmp = subset(df, df$Description == ROWS[ii])
      if(nrow(tmp) == 0 ) {   
        tmp_names = colnames(tmp)
        tmp = data.frame(matrix(rep('N/A',ncol(df)),nrow=1) )   
        colnames(tmp) = tmp_names
        tmp[1]= ROWS[ii] #want the missing expense type put into the names column
      }else{
        tmp[1,2:ncol(tmp)] = paste0(tmp[1,2:ncol(tmp)],VAL) 
      }
      tmp
    })
```

**Comment by jgQuantScripts** [comment]
Thank you @heyitsfred

**Comment by jgQuantScripts** [comment]
Pushed Version 2.0 with the modifications. Thanks for your contribution.
